[tool.poetry]
name = "news_classifier"
version = "0.1.0"
description = "Classify livedoor news by genres"
authors = ["Ida Kenichiro <ida.kenichiro@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
bokeh = "^2.0.1"
docopt = "^0.6.2"
mecab-python3 = "^0.996.5"
numpy = "^1.18.3"
python = "^3.6"
scikit-learn = "^0.22.2"
streamlit = "^0.57.3"
tensorflow = "^2.1.0"
tensorflow-estimator = "==2.1.0"
tqdm = "^4.45.0"

[tool.poetry.dev-dependencies]
black = {version = "^19.10b0", allow-prereleases = true}

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
